## You should change each of the following fields
## to customize your blog

title: Data Science Blog
description: "Dive into the world of data with me! This blog is a space where I unravel insights, share innovative projects, and explore the fascinating intersections of Data Science. From machine learning breakthroughs to captivating data visualizations, join me as we turn raw data into powerful stories and actionable ideas." 
author: Madison Garcia
author_description: "Hi, I am Madison Garcia! A proud graduate of BYU with a B.S. in Statistics and a passion for all things Data Science. My work delves into machine learning, data wrangling, and creating visually compelling insights. Whether I am crafting models or uncovering patterns in complex datasets, I thrive on solving problems and making data accessible. Connect with me on LinkedIn or drop me an email—let's talk about the exciting ways data shapes our world!"

url: https://madisongarccia.github.io ## change this to https://yourusername.github.io
baseurl: /Blog ## change this to the name of your blog repository
header_image: /assets/img/pink_banner.png ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github:  madisongarccia
    email: madisontgw@gmail.com
    linkedin: madison-garcia-b81a67262



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




